version: '3'

services:
  eureka:
    build: eureka-naming-service/target
    ports:
      - "8761:8761"
    networks:
      - default

  config:
    build: config-server/target
    ports:
      - "8888:8888"
    networks:
      - default
  
  gateway:
    build: api-gateway/target
    ports:
      - "8765:8765"
    networks:
      - default
    depends_on:
      - eureka
    environment:
      - EUREKA_SERVICE_URL=http://eureka:8761

  tracing:
    build: tracing-service/target
    ports:
      - "9411:9411"
    networks:
      - default
    depends_on:
      - eureka
    environment:
      - EUREKA_SERVICE_URL=http://eureka:8761

  auth:
    build: authorization-service/target
    ports:
      - "9000:9000"
    networks:
      - default
    environment:
      - EUREKA_SERVICE_URL=http://eureka:8761
      - DB_URL=jdbc:mysql://db:3306

  phonebook:
    build: phonebook-service/target
    ports:
      - "8080:8080"
    environment:
      - EUREKA_SERVICE_URL=http://eureka:8761
      - DB_URL=jdbc:mysql://db:3306
      - CONFIG_SERVER_URL=http://config:8888
      - GATEWAY_URL=http://gateway:8765

  contact:
    build: contact-service/target
    ports:
      - "8081:8081"
    networks:
      - default
    environment:
      - EUREKA_SERVICE_URL=http://eureka:8761
      - DB_URL=jdbc:mysql://db:3306
      - CONFIG_SERVER_URL=http://config:8888
      - GATEWAY_URL=http://gateway:8765

  ui:
    build: ui-service/target
    ports:
      - "8000:8000"
    networks:
      - default
    environment:
      - EUREKA_SERVICE_URL=http://eureka:8761
      - CONFIG_SERVER_URL=http://config:8888
      - AUTH_URL=http://auth:9000

  db:
    image: mysql
    ports:
      - "3306:3306"
    networks:
      - default
    volumes:
      - xxx:/var/lib/mysql

networks:
   default:



